# Generated by Django 5.2.3 on 2025-06-25 08:49

import django.db.models.deletion
import file.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('folder', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('size_in_bytes', models.BigIntegerField(default=0)),
                ('file', models.FileField(blank=True, null=True, upload_to=file.models.file_upload_path)),
                ('content_type', models.CharField(blank=True, max_length=255)),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='folder.folder')),
                ('root_folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='all_files', to='folder.folder')),
            ],
        ),
    ]
