# Generated by Django 5.2.3 on 2025-06-25 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0002_alter_file_folder_alter_file_root_folder'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='shareable',
            field=models.BooleanField(default=False, help_text='Whether this file can be accessed via API'),
        ),
    ]
