# Generated by Django 5.2.3 on 2025-06-25 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0003_file_shareable'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='views',
            field=models.PositiveIntegerField(default=0, help_text='Number of times this file has been viewed'),
        ),
    ]
