# Generated by Django 5.2.3 on 2025-06-25 22:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0005_alter_file_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
